### ISSUE TITLE
avoid inserting just before the hand

### ISSUE THREAD

**Issue by kurellajunior** [cacheMon/NSDI24-SIEVE#1]
Hi there,

I hope, this is the right place to contact about your SIEVE-paper. I find that idea very interesting and had the following thought:

What if you implement the underlying structure not as a queue but as a ring?

You would not insert at some random Head but always behind the hand, as long as the cache size is not reached.
in case of eviction you would replace the item to evict with the new one and move on one step with the hand.

That should reduce the miss ratio a bit in the cases where the hand is close to the head…

(as a positive side effect, no more checks if the hand points to nothing and resetting it to the tail)

**Comment by 1a1a11a** [comment]
Hi @kurellajunior, warm up is often not considered in cache eviction (since most of the time a cache is full) 
Can you elaborate on the difference between the proposal and the CLOCK algorithm? 

You can join our slack for more discussions :)  
https://join.slack.com/t/cachemon/shared_invite/zt-20pjil08z-f9d1Ui~p1gfBnsedHP9x8Q

**Comment by kurellajunior** [comment]
joined slack :)
It seems to be the CLOCK algorith. I just now learn about the cache algorithms, had no need to look inside those in the past 20 years :see_no_evil:

I am curious how the queue-sieve can be more performant than a clock. Especially as it miss rate will fluctuate depending on the relative position of the hand.

would be interesting to measure the miss rate in relation to the distance of the last request.
I expect the sieve to have a high variance while the CLOCK should be way more predictable in that measurement

**Comment by 1a1a11a** [comment]
That's what I thought, but the magic is that SIEVE is actually better :) 
There are still things we do not understand, happy to learn together
