### ISSUE TITLE
nit: Many links in NSDI24-SIEVE/libCacheSim/README.md are boken

### ISSUE THREAD

**Issue by pbokc** [cacheMon/NSDI24-SIEVE#2]
The links in the "libCacheSim features" and "Supported algorithms" point to `/NSDI24-SIEVE/blob/main/libCacheSim/<whatever>`, but the  `/NSDI24-SIEVE/blob/` directory doesn't exist.

**Comment by 1a1a11a** [comment]
Thank you! Would you like to submit a pull request?

**Comment by pbokc** [comment]
I have the code changes locally - don't think I have write access to the repo

**Comment by 1a1a11a** [comment]
You can create a PR https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
