### ISSUE TITLE
Lock and Thread Safety

### ISSUE THREAD

**Issue by LepingLi0810** [cacheMon/NSDI24-SIEVE#5]
Hi,

Thanks for the great work!

I have a question regarding the locking mechanism in SIEVE. As I understand, SIEVE eliminates the need for locking during cache hits, which significantly reduces overhead. However, I assume that locks are still required during evictions to ensure consistency.

In a multi-threaded environment, what would happen if one thread attempts to access an object that another thread is concurrently evicting? This scenario seems quite common, and in the Linux kernel, mechanisms like RCU or seqlocks are used to manage similar situations. Could you elaborate on how SIEVE ensures a consistent view of the cache in such cases?

Thank you for your time, and I look forward to your insights.

Thanks

**Comment by 1a1a11a** [comment]
Hi @LepingLi0810, Thank you for your interest! 
1. Yes, eviction still requires locking. 
2. There are different approaches to solving the conflict between reads and eviction depending on implementation and language support. For example, if you use a smart pointer for value, then it is automatically solved. Assuming there is no 
language support, one possible solution is to use an atomic refcount, which tracks the number of readers. So each read increments the counter before reading and decrements the counter after reading. During eviction, we first remove the hash table entry to prevent future reads, and then we remove the objects from the queue. The deallocation happens after the recount reaches 0.

**Comment by LepingLi0810** [comment]
Thanks for your information! This is very helpful.
